server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ProductDb
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: PRODUCT-SERVICE
  cloud:
    config: 
      uri: optional:http://localhost:8888

# eureka:
#     instance:
#         prefer-ip-address: true
#     client:
#         register-with-eureka: true
#         fetch-registry: true
#         service-url:
#           defualt-zone: http://localhost:8761/eureka
  